In [2]:
#import pandas to import and read csv file
#verify importation was successful

import pandas as pd

filename = 'medical_market_basket.csv'
mrd = pd.read_csv(filename)
mrd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15002 entries, 0 to 15001
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Presc01  7501 non-null   object
 1   Presc02  5747 non-null   object
 2   Presc03  4389 non-null   object
 3   Presc04  3345 non-null   object
 4   Presc05  2529 non-null   object
 5   Presc06  1864 non-null   object
 6   Presc07  1369 non-null   object
 7   Presc08  981 non-null    object
 8   Presc09  654 non-null    object
 9   Presc10  395 non-null    object
 10  Presc11  256 non-null    object
 11  Presc12  154 non-null    object
 12  Presc13  87 non-null     object
 13  Presc14  47 non-null     object
 14  Presc15  25 non-null     object
 15  Presc16  8 non-null      object
 16  Presc17  4 non-null      object
 17  Presc18  4 non-null      object
 18  Presc19  3 non-null      object
 19  Presc20  1 non-null      object
dtypes: object(20)
memory usage: 2.3+ MB

In [3]:
#print a random transaction from the dataset

mrd.iloc[7]

Presc01     paroxetine
Presc02    allopurinol
Presc03            NaN
Presc04            NaN
Presc05            NaN
Presc06            NaN
Presc07            NaN
Presc08            NaN
Presc09            NaN
Presc10            NaN
Presc11            NaN
Presc12            NaN
Presc13            NaN
Presc14            NaN
Presc15            NaN
Presc16            NaN
Presc17            NaN
Presc18            NaN
Presc19            NaN
Presc20            NaN
Name: 7, dtype: object

In [4]:
#check dimensions of dataset
#look at first few rows

print(mrd.shape)
mrd.head()

(15002, 20)

,Presc01,Presc02,Presc03,Presc04,Presc05,Presc06,Presc07,Presc08,Presc09,Presc10,Presc11,Presc12,Presc13,Presc14,Presc15,Presc16,Presc17,Presc18,Presc19,Presc20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,amlodipine,albuterol aerosol,allopurinol,pantoprazole,lorazepam,omeprazole,mometasone,fluconozole,gabapentin,pravastatin,cialis,losartan,metoprolol succinate XL,sulfamethoxazole,abilify,spironolactone,albuterol HFA,levofloxacin,promethazine,glipizide
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,citalopram,benicar,amphetamine salt combo xr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#drop rows where all values are 'NaN'
#recheck dimensions

mrd.dropna(how = 'all', inplace = True)
mrd.shape

(7501, 20)

In [6]:
#convert our data to a list of lists

rows = []
for i in range (0, mrd.shape[0]):
    rows.append([str(mrd.values[i,j])
for j in range (0, mrd.shape[1])])

In [7]:
#import TransactionEncoder and initialize
#create a temporary array and fit and transform
#convert to dataframe

from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
array = te.fit(rows).transform(rows)
mrd_clean = pd.DataFrame(array, columns = te.columns_)

In [8]:
#look at first few rows

mrd_clean.head()

,Duloxetine,Premarin,Yaz,abilify,acetaminophen,actonel,albuterol HFA,albuterol aerosol,alendronate,allopurinol,...,trazodone HCI,triamcinolone Ace topical,triamterene,trimethoprim DS,valaciclovir,valsartan,venlafaxine XR,verapamil SR,viagra,zolpidem
0,False,False,False,True,False,False,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
#drop all null columns from our transformed dataset
#check first few rows again
#recheck dimensions to verify everything looks good

mrd_cleaned = mrd_clean.drop(['nan'], axis = 1)
mrd_cleaned.head()
print(mrd_cleaned.shape)

(7501, 119)

In [10]:
#export transformed dataset to csv for submission

mrd_cleaned.to_csv('mrd_cleaned.csv', index = False)

In [11]:
#import apriori and association rules
#use support of 0.03 to find itemsets occurring in at least 3% of all transactions

from mlxtend.frequent_patterns import apriori, association_rules

freq_itemsets = apriori(mrd_cleaned, min_support = 0.03, use_colnames = True)
freq_itemsets.head(5)

    support       itemsets
0  0.046794     (Premarin)
1  0.238368      (abilify)
2  0.033329  (allopurinol)
3  0.079323   (alprazolam)
4  0.071457   (amlodipine)

In [12]:
#create rules table using lift as the metric
#look at first few rows of this table

rules_table = association_rules(freq_itemsets, metric = 'lift', min_threshold = 1.0)
rules_table.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(abilify),(amphetamine salt combo xr),0.238368,0.179709,0.050927,0.213647,1.188845,1.0,0.008090,1.043158,0.208562,0.138707,0.041372,0.248515
1,(amphetamine salt combo xr),(abilify),0.179709,0.238368,0.050927,0.283383,1.188845,1.0,0.008090,1.062815,0.193648,0.138707,0.059103,0.248515
2,(atorvastatin),(abilify),0.129583,0.238368,0.047994,0.370370,1.553774,1.0,0.017105,1.209650,0.409465,0.150000,0.173315,0.285856
3,(abilify),(atorvastatin),0.238368,0.129583,0.047994,0.201342,1.553774,1.0,0.017105,1.089850,0.467950,0.150000,0.082443,0.285856
4,(abilify),(carvedilol),0.238368,0.174110,0.059725,0.250559,1.439085,1.0,0.018223,1.102008,0.400606,0.169312,0.092566,0.296796

In [13]:
#generate top 3 rules from rules table, sorting by lift
#only print values we are interested in for this top 3

t3 = rules_table.sort_values('lift', ascending = False)
print(t3[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(3))

     antecedents   consequents   support  confidence      lift
28  (carvedilol)  (lisinopril)  0.039195    0.225115  2.291162
29  (lisinopril)  (carvedilol)  0.039195    0.398915  2.291162
10     (abilify)  (lisinopril)  0.040928    0.171700  1.747522